# ============== DEPLOYMENT VARIABLES ============================
MONITORING_ENABLED: true
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "info"
TRACING_ENABLED: false
TRACING_HOST: 'nc-diagnostic-agent'
TRACING_SAMPLER_RATELIMITING: 10

EXECUTION_MODE: active

K8S_SERVICE_TYPE: 'HEADLESS'

MAAS_AGENT_NAMESPACE_ISOLATION_ENABLED: true
CONSUL_ENABLED: false
CONSUL_URL: ''
