---
kind: ConfigMap
apiVersion: v1
metadata:
    name: "{{ .Values.SERVICE_NAME }}.monitoring-config"
    labels:
      app.kubernetes.io/part-of: 'Cloud-Core'
      app.kubernetes.io/managed-by: 'saasDeployer'
data:
    url.health: http://%(ip)s:8080/health
    prometheus.url.metrics: http://%(ip)s:8080/prometheus
