name: Go build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@v1.0.9
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    needs: [build]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.0.9
    with:
      dry-run: false
